server {
    listen 80;
    server_name insidememory.org www.insidememory.org;

    location = / {
        return 404;
    }

    location = /event-memory-orchestration {
        return 301 /event-memory-orchestration/;
    }

    location /event-memory-orchestration/ {
        alias /usr/share/nginx/html/landings/event-memory-orchestration/;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
